import Head from "next/head";
// import { useAuth0 } from "@auth0/auth0-react";
// import { useMutation } from "../convex/_generated/react";
// import { useEffect, useState } from "react";

import Dashboard from "./components/Dashboard";

export default function Home() {
  // const { user } = useAuth0();
  // const [userId, setUserId] = useState(null);
  // const storeUser = useMutation("storeUser");
  // // Call the `storeUser` mutation function to store
  // // the current user in the `users` table and return the `Id` value.
  // useEffect(() => {
  //   // Store the user in the database.
  //   // Recall that `storeUser` gets the user information via the `auth`
  //   // object on the server. You don't need to pass anything manually here.
  //   async function createUser() {
  //     const id = await storeUser();
  //     setUserId(id);
  //   }
  //   createUser();
  //   return () => setUserId(null);
  // }, [storeUser]);

  return (
    <div >
      <Head>
        <title>BeetWarden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{maxHeight: "100vh"}} >
        <Dashboard />
      </main>


    </div>
  );
}
