import Head from "next/head";
import { useAuth0 } from "@auth0/auth0-react";
import { Button, Flex, Title, Text, List, Grid, Card } from "@mantine/core";
import Link from "next/link";
import Image from "next/image";
import { useMediaQuery } from "@mantine/hooks";
import beetPic from "../../public/beetroot.jpg";

export default function Login() {
  const { isLoading, loginWithRedirect } = useAuth0();
  const isMobile = useMediaQuery("(min-width: 900px)");

  return (
    <div>
      <Head>
        <title>BeetWarden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid styles={{ maxHeight: "100vh" }}>
          <Grid.Col md={4} p={0}>
            <Flex
              mih={"100vh"}
              gap="lg"
              px={32}
              justify="center"
              align="center"
              direction="column"
              wrap="wrap"
            >
              <Card>
              <Title order={2} align="center" mt="md" mb={10}>
                Welcome to BeetWarden!
              </Title>
              <Text color="dimmed" align="center" mt={30}>
                This is a password manager. It has nothing to do with beets.
              </Text>
              <Text color="dimmed" align="center" mb={30}>
                Fact: Bears eat beets.
              </Text>

              <Text>
                BeetWarden is an exercise where BaaS is applied with the help of{" "}
                <Link href="https://www.convex.dev/">Convex</Link>. If you like
                to take a look inside, you can use a google account, there is a
                connection through Auth0, or, you can use this test account:
              </Text>
              <List>
                <List.Item>
                  <Text fw={700}>Username: </Text> spongebob@squarepants.com{" "}
                </List.Item>
                <List.Item>
                  <Text fw={700}>Password: </Text> 1LovePatrick!
                </List.Item>
              </List>
              <Text>
                The source code is on{" "}
                <Link href="https://github.com/andres039/beetWarden">
                  GitHub
                </Link>
                . Thank you for taking the time to look at this project. Any
                feedback is appreciated, you may contact me on{" "}
                <Link href="https://www.linkedin.com/in/andresbeltrangarcia/">
                  LinkedIn
                </Link>
                .
              </Text>
              <Button
                fullWidth
                mt="xl"
                size="md"
                variant="gradient"
                gradient={{ from: "teal", to: "lime", deg: 105 }}
                disabled={isLoading}
                onClick={loginWithRedirect}
              >
                Login / Signup
              </Button>
              </Card>
            </Flex>
          </Grid.Col>
          {isMobile && (
            <Grid.Col md={8} p={0}>
              <div
                style={{
                  position: "relative",
                  minHeight: "100vh",
                  display: "block",
                }}
              >
                <Image src={beetPic} alt="picture of beets" fill priority placeholder="blur"/>
              </div>
            </Grid.Col>
          )}
        </Grid>
      </main>
    </div>
  );
}
